kind: Service
apiVersion: v1
metadata:
  name: peer1-org2
  labels:
    app: peer1-org2
spec:
  selector:
    name: peer1-org2
  type: ClusterIP
  ports:
    - name: grpc
      port: 8051
      protocol: TCP
    - name: event
      port: 8061
      protocol: TCP
    - name: couchdb
      port: 5984
      protocol: TCP

---
#---------------- peer1 org2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer1-org2
    metrics-service: "true"
  name: peer1-org2-metrics
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    name: peer1-org2
